export { default as Home } from './Home'
export { default as Signup } from './signupPage'
export { default as Login } from './loginPage'
export { default as Catalog } from './catalogPage'
export { default as Course } from './courseList'
export { default as Product } from './courseDetails'